---
- name: Install AnyDesk and Visual Studio Code on Windows
  hosts: 172.16.0.67
  gather_facts: no
  tasks:
    - name: Install Visual Studio Code
      chocolatey.chocolatey.win_chocolatey:
        name: vscode
        state: present
        params: "--accept-license"
