---
- name: Install software on Windows
  hosts: 172.16.0.67
  tasks:
    - name: Ensure Chocolatey is installed
      community.windows.win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Git using Chocolatey
      community.windows.win_chocolatey:
        name: git
        state: present
