---
- name: Install VLC media player and AnyDesk on Windows
  hosts: 172.16.0.67
  gather_facts: no
  tasks:
    - name: Install VLC media player
      win_shell: |
        choco install vlc -y

    - name: Download AnyDesk installer
      win_get_url:
        url: https://download.anydesk.com/AnyDesk.exe
        dest: C:\Temp\AnyDesk.exe

    - name: Install AnyDesk
      win_command: C:\Temp\AnyDesk.exe /S
