---
- name: Install free software on Windows
  hosts: windows_servers
  tasks:
    - name: Install VLC Media Player
      win_chocolatey:
        name: vlc
        state: present

    - name: Install 7-Zip
      win_chocolatey:
        name: 7zip
        state: present

    - name: Install Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: present
