- name: Install AnyDesk on Windows
  hosts: 172.16.0.67
  gather_facts: no
  tasks:
    - name: Download AnyDesk installer
      win_get_url:
        url: https://download.anydesk.com/AnyDesk.exe
        dest: C:\Temp\AnyDesk.exe

    - name: Install Visual Studio Code
      chocolatey.chocolatey.win_chocolatey:
        name: vscode
        state: present
        params: "--accept-license"
