---
- name: Install AnyDesk, VLC Media Player, and MobaXterm
  hosts: 172.16.0.67
  tasks:
    - name: Uninstall Visual Studio Code using Chocolatey
      win_chocolatey:
        name: vscode
        state: absent

    - name: Ensure Visual Studio Code is uninstalled using PowerShell
      win_shell: |
        $vscode = Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -like "*Microsoft Visual Studio Code*" }
        if ($vscode) {
            $vscode.Uninstall()
        } else {
            Write-Output "Visual Studio Code is not installed."
        }
      args:
        executable: powershell.exe
