- name: Install software
  hosts: windows_machines  # Replace with your target windows machine group

  tasks:
    # Task 1: Install software with traditional installer (MSI/EXE)
    - name: Install software with MSI/EXE (if installer path provided)
      win_package:
        path: "{{ software_installer_path.vars }}"  # Get path from a variable
        state: present
      when: software_installer_path is defined

    # Task 2: Install software with Chocolatey (if Chocolatey is already installed)
    - name: Install software with Chocolatey
      win_chocolatey:
        name: "{{ software_name.vars }}"  # Get name from a variable
        state: present
      when:
        - not software_installer_path is defined  # Only run if no MSI/EXE path provided
        - win_chocolatey.chocolatey.version is defined  # Check if Chocolatey is installed

  vars:
    # Define variables for software installer path and name based on your needs
    software_installer_path: ""
    software_name: ""
