---
- name: Install Chocolatey and Visual Studio Code on Windows
  hosts: 172.16.0.67
  gather_facts: no
  tasks:
    - name: Download Chocolatey installer script
      ansible.windows.win_get_url:
        url: https://chocolatey.org/install.ps1
        dest: C:\Temp\install_chocolatey.ps1

    - name: Install Chocolatey
      ansible.windows.win_shell: |
        powershell.exe -ExecutionPolicy Bypass -File C:\Temp\install_chocolatey.ps1
      args:
        creates: C:\ProgramData\chocolatey\bin\choco.exe

    - name: Ensure Chocolatey is in the PATH
      ansible.windows.win_environment:
        state: present
        name: PATH
        value: C:\ProgramData\chocolatey\bin
        level: machine

    - name: Refresh environment variables to include Chocolatey
      ansible.windows.win_shell: |
        powershell.exe -noprofile -command "[System.Environment]::SetEnvironmentVariable('Path', [System.Environment]::GetEnvironmentVariable('Path', 'Machine'), 'Process')"

    - name: Install Visual Studio Code using Chocolatey
      ansible.windows.win_shell: |
        choco install vscode --yes --accept-license
