---
- name: Install AnyDesk and VLC Media Player on Windows
  hosts: 172.16.0.67
  tasks:
    - name: Install AnyDesk
      win_chocolatey:
        name: anydesk
        state: present

    - name: Install VLC Media Player
      win_chocolatey:
        name: vlc
        state: present
