---
- name: Install Visual Studio Code using Chocolatey
  hosts: 172.16.0.67
  tasks:
    - name: Install Chocolatey if not already installed
      win_command: >
        @"C:\Windows\System32\WindowsPowerShell\v1.0" -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command " [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"  # Install Chocolatey if not already installed

    - name: Install Visual Studio Code
      win_chocolatey:
        name: vscode
        state: present
