- name: Install Common Free Software with Chocolatey
  hosts: 172.16.0.67
  gather_facts: false
  tasks:
    - name: Install Chocolatey (if not already installed)
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install common free software packages
      win_chocolatey:
        name: "{{ item }}"
        state: present
      loop:
        - googlechrome
        - firefox
        - vscode
        - notepadplusplus
        - git
