---
- name: Install Chocolatey and Visual Studio Code on Windows
  hosts: 172.16.0.67
  gather_facts: no
  tasks:
    - name: Download Chocolatey installer script
      ansible.windows.win_get_url:
        url: https://chocolatey.org/install.ps1
        dest: C:\Temp\install_chocolatey.ps1

    - name: Install Chocolatey
      ansible.windows.win_shell: |
        C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -File C:\Temp\install_chocolatey.ps1
      args:
        creates: C:\ProgramData\chocolatey\bin\choco.exe

    - name: Ensure Chocolatey is in the PATH
      ansible.windows.win_environment:
        state: present
        name: PATH
        value: C:\ProgramData\chocolatey\bin
        level: machine

    - name: Install Visual Studio Code using Chocolatey
      ansible.windows.win_shell: |
        C:\ProgramData\chocolatey\bin\choco.exe install vscode --yes --accept-license
