---
- name: Install MeshCentral Agent
  hosts: 172.16.0.67
  tasks:
    - name: Ensure Chocolatey is installed
      win_chocolatey:
        name: chocolatey
        state: present

    - name: Install NSSM (Non-Sucking Service Manager)
      win_chocolatey:
        name: nssm
        state: present

    - name: Download MeshCentral Agent
      win_get_url:
        url: "https://172.16.0.93/meshagents?id=4"
        dest: C:\\Temp\\meshagent.exe

    - name: Install MeshCentral Agent
      win_command: "C:\\Temp\\meshagent.exe -install"
      args:
        creates: "C:\\Program Files\\Mesh Agent\\meshagent.exe"

    - name: Ensure MeshCentral Agent service is started
      win_service:
        name: "Mesh Agent"
        start_mode: auto
        state: started

    - name: Open Firewall port for MeshCentral Agent
      win_firewall_rule:
        name: "MeshCentral Agent"
        enable: yes
        direction: in
        action: allow
        protocol: tcp
        localport: 443
